general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[window]
padding.x = 20
padding.y = 20
opacity = 0.9
