general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[window]
padding.x = 10
padding.y = 10
opacity = 0.9
dynamic_padding = true
