[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = next

[default_session]
command = "start-hyprland -- -c /etc/greetd/hyprland.conf &> /dev/null"
user = "greeter"
